server:
  port: 80
  context-path: /
  

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.14.112.198:3306/db_jxc
      username: jxc
      password: 123456

   http:
      encoding:
      force: true
      charset: UTF-8
      enabled: true
   server:
      tomcat:
      uri-encoding: UTF-8


   jpa:
     hibernate.ddl-auto: update
     show-sql: true

   thymeleaf:
      prefix: classpath:/static/
      suffix: .html
      context-type: text/html
      encoding: UTF-8
      enabled: true

